name: Deploy via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: SFTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: sftp
          port: 22 # Default SFTP port
          server-dir: /public_html/wp-content/themes/timber-starter-theme/ # Replace with your remote directory
          # Exclude files/directories you don't want to upload
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            README.md
