name: Deploy to WordPress
on:
  push:
    branches:
      - main
jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: push to cloudways
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 164.90.133.111
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: sftp
        port: 22
        server-dir: /public_html/wp-content/themes/timber-starter-theme/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          README.md
          .env
          .env.*
